#!/bin/bash
#PBS -N bowtie_metabolicmarker_MG
#PBS -l select=1:ncpus=40:mem=372gb,walltime=72:00:00
#PBS -q camplab
#PBS -m abe
#PBS -M jojyj@clemson.edu
#PBS -k oe

module load  prokka/1.14.5


# Directory containing your FASTA files
fasta_dir="/zfs/camplab/Jojy/MTM2_RoL/mg_all_asembly"

# Directory to store Prokka output
output_dir="/zfs/camplab/Jojy/MTM2_RoL/prokka"

# Iterate over each FASTA file in the directory
for fasta_file in "$fasta_dir"/*.fa; do
    # Extract the base name of the file (without extension)
    base_name=$(basename "$fasta_file" .fa)
    
    # Create a directory for Prokka output
    mkdir -p "$output_dir/$base_name"

    # Run Prokka on the current FASTA file
    prokka --outdir "$output_dir/$base_name" "$fasta_file"
done
